lol/urls.py
from django.contrib import admin
from django.urls import path, re_path
from mainapp import views as mainapp
from authapp import views as authapp
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static


urlpatterns = [
    path('', authapp.index, name='index'),
    path('home/', mainapp.index, name="home"),
    path('collection/', include('collectapp.urls', namespace='collection')),
    path('loot/', include('lootapp.urls', namespace="loot")),
    path('store/', include('storeapp.urls', namespace="store")),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('social_django.urls', namespace='social')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('order/', include('orderapp.urls', namespace='order'))

    
    # path('control/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

orderapp/urls.py
from django.urls import path
import orderapp.views as orderapp

app_name = 'orderapp'

urlpatterns = [
    path('', orderapp.OrderListView.as_view(), name='list'),
    path('create/', orderapp.OrderCreateView.as_view(), name='create'),
    path('read/<int:pk>/', orderapp.OrderDetailView.as_view(), name='read'),
    path('update/<int:pk>/', orderapp.OrderUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', orderapp.OrderDeleteView.as_view(), name='delete'),
    path('proceed/<int:pk>/', orderapp.order_sending_to_payment, name='proceed'),
    path('payment/<int:pk>/', orderapp.order_payment, name='payment'),
    path('material/price/<int:pk>/', orderapp.get_material_price, name='get_material_price')
]

storeapp/urls.py
from django.urls import path
import storeapp.views as storeapp

app_name = 'storeapp'

urlpatterns = [
    path('', storeapp.store, name='index'),
    path('<str:name>/', storeapp.store, name='category'),
    path('<str:name>/<str:role>/', storeapp.store, name='champs'),
    path('add/<str:cat>/<int:pk>/', storeapp.add, name='add'),
]

storeapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404

from lootapp.models import PurchasedMaterial
from mainapp.models import CollectionCategory, Champion, Skin
from basketapp.models import ChampionBasket, SkinBasket
from django.db.models import Q
from django.http import Http404
from django.conf import settings
from django.core.cache import cache


def get_categories():
    if settings.LOW_CACHE:
        key = 'categories'
        categories = cache.get(key)
        if categories is None:
            categories = CollectionCategory.objects.all()
            cache.set(key, categories)
        return categories
    return CollectionCategory.objects.all()


@login_required
def store(request, name=None, role='all'):

    basket_champ = ChampionBasket.objects.filter(user=request.user).first()
    basket_skin = SkinBasket.objects.filter(user=request.user).first()

    if basket_champ:
        owned_champs = basket_champ.get_owned()
        champ_total_cost_rp = basket_champ.get_total_cost[0]
        champ_total_cost_be = basket_champ.get_total_cost[1]

        if basket_skin:
            owned_skins = basket_skin.get_owned()
            skin_total_cost = basket_skin.get_total_cost
        else:
            owned_skins = SkinBasket.objects.none()
            skin_total_cost = 0
    else:
        owned_champs = ChampionBasket.objects.none()
        owned_skins = SkinBasket.objects.none()
        champ_total_cost_rp = 0
        champ_total_cost_be = 0
        skin_total_cost = 0

    material_total_cost = sum(map(lambda x: x.get_total_cost, PurchasedMaterial.objects.filter(user=request.user)))

    total_cost_rp = champ_total_cost_rp + skin_total_cost + material_total_cost

    roles = {
        'slayer': ['assassin', 'skirmisher'],
        'fighter': ['juggernaut', 'diver'],
        'mage': ['battlemage', 'burst', 'artillery'],
        'marksman': ['marksman'],
        'tank': ['vanguard', 'warden'],
        'support': ['catcher', 'enchanter']
    }

    context = {
        'title': 'Store',
        'categories': get_categories(),
        'champions': Champion.objects.filter(~Q(pk__in=owned_champs)).order_by('name'),
        'roles': roles,
        'skins': Skin.objects.filter(~Q(pk__in=owned_skins)).order_by('champion__name', 'name'),
        'owned_champs': owned_champs,
        'owned_skins': owned_skins,
        'total_cost_rp': total_cost_rp,
        'total_cost_be': champ_total_cost_be
    }

    if role != 'all':

        if role not in roles:
            raise Http404

        name = 'champions'

        champions = context['champions'].filter(Q(role__in=roles[role]) | Q(role_b__in=roles[role]))
        context['champions'] = champions

    if name is None:
        page = 'storeapp/store.html'
    elif name == 'loot':
        page = 'storeapp/loot.html'
    else:
        get_object_or_404(CollectionCategory, name=name)
        page = f'storeapp/{name}.html'
        context['title'] = name.title()

    return render(request, page, context=context)


@login_required
def add(request, cat=None, pk=None):

    if cat == "champions":
        product = get_object_or_404(Champion, pk=pk)
    elif cat == "skins":
        product = get_object_or_404(Skin, pk=pk)

    context = {
        'title': product.name,
        'product': product,
        'owned_skins': SkinBasket.objects.filter(user=request.user).values_list('skin', flat=True),
        'owned_champs': ChampionBasket.objects.filter(user=request.user).values_list('champion', flat=True)
    }

    page = f'storeapp/{cat[:-1]}.html'

    return render(request, page, context=context)

storeapp/templates/storeapp/champion.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block header %}
{% endblock %}

{% block content %}
    <div class="add_content">
        <img src="{{ product.image.url }}" alt="{{ product.name }}" class="champion_img">
        <h4 class="name">{{ product.name }}</h4>
        {% if product.pk not in owned_champs %}
        <div class="buy_block">
            <a href="{% url 'basket:add' cat='champions' pk=product.pk method='rp' %}" class="link">
            <div class="buy_subblock">
                <img src="{% static 'img/RP.png' %}" alt="RP" class="price_img">
                <p class="price">{{ product.price_rp }}</p>
            </div>
            </a>
            <a href="{% url 'basket:add' cat='champions' pk=product.pk method='be' %}" class="link">
            <div class="buy_subblock">
                <img src="{% static 'img/Blue_Essence.png' %}" alt="BE" class="price_img">
                <p class="price">{{ product.price_be }}</p>
            </div>
            </a>
        </div>
        {% else %}
        <div class="buy_block buy_block_one">
            <div class="buy_subblock">
                <p class="price">OWNED</p>
            </div>
        </div>
        {% endif %}
        <a href="{% url 'store:category' 'champions' %}" class="back">Go to store</a>
    </div>
{% endblock %}

storeapp/templates/storeapp/champions.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
{% include 'storeapp/includes/inc_store_menu.html' %}
<div class="store_content">
    <div class="content_left">
        <input type="text" placeholder="Search" class="search">
        <a href="#" class="show_unowned">Show Owned</a>
        <ul class="selection">
            <li><a href="#" class="selection_link">Price (RP)</a></li>
            <li><a href="#" class="selection_link">Price (RP) desc</a></li>
            <li><a href="#" class="selection_link">Price (BE)</a></li>
            <li><a href="#" class="selection_link">Price (BE) desc</a></li>
            <li><a href="#" class="selection_link">Alphabet</a></li>
            <li><a href="#" class="selection_link">Alphabet desc</a></li>
        </ul>
        <ul class="selection">
            {% for role in roles %}
            <li>
                <a href="{% url 'store:champs' name='champions' role=role %}" class="selection_link">{{ role|title }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="content_right">
        {% for champ in champions %}
        <a {% if champ.pk not in owned_champs %}href="{% url 'store:add' cat='champions' pk=champ.pk %}"{% else %}
           href="#"{% endif %} class="store_link">
            <div class="champion">
                <img src="{{ champ.image.url }}" alt="{{ champ.name }}" {% if champ.pk not in owned_champs %}
                     class="champion_img not_owned"{% else %}class="champion_img"{% endif %}>
                <p class="champion_name">{{ champ.name|title }}</p>
                <div class="champion_price_big">
                    <div class="champion_price_small">
                        <img src="{% static 'img/RP.png' %}" alt="RP" class="champion_price_img">
                        <p class="champion_price">{{ champ.price_rp }}</p>
                    </div>
                    <div class="champion_price_small">
                        <img src="{% static 'img/Blue_Essence.png' %}" alt="BE" class="champion_price_img">
                        <p class="champion_price">{{ champ.price_be }}</p>
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

storeapp/templates/storeapp/loot.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
{% include 'storeapp/includes/inc_store_menu.html' %}
<div class="purchase_block">
    <a href="{% url 'order:list' %}" class='purchase_link'>Purchase</a>
</div>
{% endblock %}

storeapp/templates/storeapp/skin.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block header %}
{% endblock %}

{% block content %}
    <div class="add_content">
        <img src="{{ product.image.url }}" alt="{{ product.name }}" class="champion_img">
        <h4 class="name">{{ product.name }}</h4>
        {% if product.pk not in owned_skins and product.champion.pk in owned_champs %}
        <div class="buy_block buy_block_one">
            <a href="{% url 'basket:add' cat='skins' pk=product.pk method='rp' %}" class="link">
            <div class="buy_subblock">
                <img src="{% static 'img/RP.png' %}" alt="RP" class="price_img">
                <p class="price">{{ product.price_rp }}</p>
            </div>
            </a>
        </div>
        {% elif product.champion.pk not in owned_champs %}
        <div class="buy_block buy_block_one">
            <div class="buy_subblock">
                <a href="{% url 'store:add' cat='champions' pk=product.champion.pk %}" class="price link">BUY CHAMPION</a>
            </div>
        </div>
        {% else %}
        <div class="buy_block buy_block_one">
            <div class="buy_subblock">
                <p class="price">OWNED</p>
            </div>
        </div>
        {% endif %}
        <a href="{% url 'store:category' 'skins' %}" class="back">Go to store</a>
    </div>
{% endblock %}

storeapp/templates/storeapp/skins.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
{% include 'storeapp/includes/inc_store_menu.html' %}
<div class="store_content">
    <div class="content_left">
        <input type="text" placeholder="Search" class="search">
        <a href="#" class="show_unowned">Show Owned</a>
        <a href="#" class="show_unowned">Champion Owned</a>
        <ul class="selection">
            <li><a href="#" class="selection_link">Price (RP)</a></li>
            <li><a href="#" class="selection_link">Price (RP) desc</a></li>
            <li><a href="#" class="selection_link">Price (BE)</a></li>
            <li><a href="#" class="selection_link">Price (BE) desc</a></li>
            <li><a href="#" class="selection_link">Alphabet</a></li>
            <li><a href="#" class="selection_link">Alphabet desc</a></li>
        </ul>
    </div>
    <div class="content_right">
        {% for skin in skins %}
        <a {% if skin.pk not in owned_skins %}href="{% url 'store:add' cat='skins' pk=skin.pk %}"{% else %}
        href="#"{% endif %} class="store_link">
        <div class="champion">
            <img src="{{ skin.image.url }}" alt="{{ skin.name }}" {% if skin.pk not in owned_skins %}
                     class="champion_img not_owned"{% else %}class="champion_img"{% endif %}>
            <p class="champion_name">{{ skin.name|title }}</p>
            <div class="champion_price_big only_rp">
                <div class="champion_price_small">
                    <img src="{% static 'img/RP.png' %}" alt="RP" class="champion_price_img">
                    <p class="champion_price">{{ skin.price_rp }}</p>
                </div>
            </div>
        </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

storeapp/templates/storeapp/store.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
{% include 'storeapp/includes/inc_store_menu.html' %}
<div class="store_content">
    <p class="total_cost">You have spent: {{ total_cost_rp }} RP</p>
    <p class="total_cost">You have spent: {{ total_cost_be }} BE</p>
</div>
{% endblock %}