adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', adminapp.user_list, name='user_list'),
    path('users/read/<int:page>/', adminapp.user_list, name='user_page'),
    path('users/update/<int:pk>/', adminapp.user_edit, name='user_edit'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),
    path('users/detail/<int:pk>/', adminapp.UserDetailView.as_view(), name='user_detail'),

    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.category_list, name='category_list'),
    path('categories/update/<int:pk>/', adminapp.category_edit, name='category_edit'),
    path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    path('champions/create/', adminapp.ChampionCreateView.as_view(), name='champion_create'),
    path('champions/read/', adminapp.ChampionListView.as_view(), name='champion_list'),
    path('champions/read/<int:page>/', adminapp.ChampionListView.as_view(), name='champion_page'),
    path('champions/update/<int:pk>/', adminapp.ChampionUpdateView.as_view(), name='champion_edit'),
    path('champions/delete/<int:pk>/', adminapp.ChampionDeleteView.as_view(), name='champion_delete'),
    path('champions/detail/<int:pk>/', adminapp.ChampionDetailView.as_view(), name='champion_detail'),

    path('skins/create/', adminapp.SkinCreateView.as_view(), name='skin_create'),
    path('skins/read/', adminapp.SkinListView.as_view(), name='skin_list'),
    path('skins/read/<int:page>/', adminapp.SkinListView.as_view(), name='skin_page'),
    path('skins/update/<int:pk>/', adminapp.SkinUpdateView.as_view(), name='skin_edit'),
    path('skins/delete/<int:pk>/', adminapp.SkinDeleteView.as_view(), name='skin_delete'),
    path('skins/detail/<int:pk>/', adminapp.SkinDetailView.as_view(), name='skin_detail')
]

lol/urls.py
from django.contrib import admin
from django.urls import path, re_path
from mainapp import views as mainapp
from authapp import views as authapp
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static


urlpatterns = [
    path('', authapp.index, name='index'),
    path('home/', mainapp.index, name="home"),
    path('collection/', include('collectapp.urls', namespace='collection')),
    path('loot/', include('lootapp.urls', namespace="loot")),
    path('store/', include('storeapp.urls', namespace="store")),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('social_django.urls', namespace='social')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('order/', include('orderapp.urls', namespace='order'))

    
    # path('control/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from authapp.forms import PlayerEditForm
from authapp.models import Player
from django import forms

from mainapp.models import CollectionCategory, Champion, Skin


class PlayerEditAdminForm(PlayerEditForm):

    class Meta:
        model = Player
        fields = '__all__'


class CategoryEditForm(forms.ModelForm):

    class Meta:
        model = CollectionCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ChampionEditForm(forms.ModelForm):

    class Meta:
        model = Champion
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class SkinEditForm(forms.ModelForm):

    class Meta:
        model = Skin
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, UpdateView, CreateView, DeleteView, DetailView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from adminapp.forms import PlayerEditAdminForm, CategoryEditForm, ChampionEditForm, SkinEditForm
from authapp.models import Player
from mainapp.models import Champion, Skin
from authapp.forms import PlayerRegisterForm
from mainapp.models import CollectionCategory
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


class AccessMixin:

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    if request.method == 'POST':
        user_form = PlayerRegisterForm(request.POST, request.FILES)

        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('admin:user_list'))
    else:
        user_form = PlayerRegisterForm()

    context = {
        'title': 'create user',
        'form': user_form
    }
    return render(request, 'adminapp/user_edit.html', context=context)


@user_passes_test(lambda u: u.is_superuser)
def user_list(request, page=1):

    paginator = Paginator(Player.objects.all().order_by('-is_active', 'nickname'), 9)
    try:
        users_paginator = paginator.page(page)
    except PageNotAnInteger:
        users_paginator = paginator.page(1)
    except EmptyPage:
        users_paginator = paginator.page(paginator.num_pages)

    context = {
        'title': 'users',
        'users': users_paginator
    }
    return render(request, 'adminapp/user_list.html', context=context)


@user_passes_test(lambda u: u.is_superuser)
def user_edit(request, pk=None):
    current_user = Player.objects.get(pk=pk)
    if request.method == 'POST':
        user_form = PlayerEditAdminForm(request.POST, request.FILES, instance=current_user)

        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('admin:user_list'))
    else:
        user_form = PlayerEditAdminForm(instance=current_user)
    context = {
        'title': 'edit user',
        'form': user_form,
        'user': current_user
    }
    return render(request, 'adminapp/user_edit.html', context=context)


class UserDetailView(AccessMixin, DetailView):
    model = Player
    template_name = 'adminapp/user.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Player.objects.get(pk=self.kwargs['pk']).nickname

        return context


@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk=None):
    current_user = get_object_or_404(Player, pk=pk)

    if request.method == 'POST':
        if current_user.is_active:
            current_user.is_active = False
        else:
            current_user.is_active = True
        current_user.save()
        return HttpResponseRedirect(reverse('admin:user_list'))
    context = {
        'title': 'ban user',
        'user': current_user
    }
    return render(request, 'adminapp/user_ban.html', context=context)


@user_passes_test(lambda u: u.is_superuser)
def category_create(request):
    if request.method == 'POST':
        category_form = CategoryEditForm(request.POST, request.FILES)

        if category_form.is_valid():
            category_form.save()
            return HttpResponseRedirect(reverse('admin:category_list'))
    else:
        category_form = CategoryEditForm()

    context = {
        'title': 'create category',
        'form': category_form
    }
    return render(request, 'adminapp/category_edit.html', context=context)


@user_passes_test(lambda u: u.is_superuser)
def category_list(request):
    context = {
        'title': 'categories',
        'categories': CollectionCategory.objects.all()
    }
    return render(request, 'adminapp/category_list.html', context=context)


@user_passes_test(lambda u: u.is_superuser)
def category_edit(request, pk=None):
    category = CollectionCategory.objects.get(pk=pk)
    if request.method == 'POST':
        category_form = CategoryEditForm(request.POST, request.FILES, instance=category)

        if category_form.is_valid():
            category_form.save()
            return HttpResponseRedirect(reverse('admin:category_list'))
    else:
        category_form = CategoryEditForm(instance=category)
    context = {
        'title': 'edit category',
        'form': category_form,
        'category': category
    }
    return render(request, 'adminapp/category_edit.html', context=context)


@user_passes_test(lambda u: u.is_superuser)
def category_delete(request, pk=None):
    category = get_object_or_404(CollectionCategory, pk=pk)

    if request.method == 'POST':
        category.delete()
        return HttpResponseRedirect(reverse('admin:category_list'))
    context = {
        'title': 'delete category',
        'category': category
    }
    return render(request, 'adminapp/category_delete.html', context=context)


class ChampionCreateView(AccessMixin, CreateView):
    model = Champion
    template_name = 'adminapp/champion_edit.html'
    success_url = reverse_lazy('admin:champion_list')
    form_class = ChampionEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'create champion'
        context['category'] = 'champions'

        return context


class ChampionListView(AccessMixin, ListView):
    model = Champion
    template_name = 'adminapp/champion_list.html'
    paginate_by = 9

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'champions'
        context['category'] = 'champions'

        return context

    def get_queryset(self):
        return Champion.objects.all().order_by('name')


class ChampionUpdateView(AccessMixin, UpdateView):
    model = Champion
    template_name = 'adminapp/champion_edit.html'
    success_url = reverse_lazy('admin:champion_list')
    form_class = ChampionEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'edit champion'
        context['category'] = 'champions'

        return context


class ChampionDeleteView(AccessMixin, DeleteView):
    model = Champion
    template_name = 'adminapp/champion_delete.html'
    success_url = reverse_lazy('admin:champion_list')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Champion.objects.get(pk=self.kwargs['pk']).name
        context['category'] = 'champions'

        return context


class ChampionDetailView(AccessMixin, DetailView):
    model = Champion
    template_name = 'adminapp/champion.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Champion.objects.get(pk=self.kwargs['pk']).name
        context['category'] = 'champions'

        return context


class SkinCreateView(AccessMixin, CreateView):
    model = Skin
    template_name = 'adminapp/skin_edit.html'
    success_url = reverse_lazy('admin:skin_list')
    form_class = SkinEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'create skin'
        context['category'] = 'skins'

        return context


class SkinListView(AccessMixin, ListView):
    model = Skin
    template_name = 'adminapp/skin_list.html'
    paginate_by = 9

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'skins'
        context['category'] = 'skins'

        return context

    def get_queryset(self):
        return Skin.objects.all().order_by('champion__name', 'name')


class SkinUpdateView(AccessMixin, UpdateView):
    model = Skin
    template_name = 'adminapp/skin_edit.html'
    success_url = reverse_lazy('admin:skin_list')
    form_class = SkinEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'edit skin'
        context['category'] = 'skins'

        return context


class SkinDeleteView(AccessMixin, DeleteView):
    model = Skin
    template_name = 'adminapp/skin_delete.html'
    success_url = reverse_lazy('admin:skin_list')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Skin.objects.get(pk=self.kwargs['pk']).name
        context['category'] = 'skins'

        return context


class SkinDetailView(AccessMixin, DetailView):
    model = Skin
    template_name = 'adminapp/skin.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Skin.objects.get(pk=self.kwargs['pk']).name
        context['category'] = 'skins'

        return context

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="container_auth">
<form action="{% url 'admin:category_delete' pk=category.pk %}" class="auth_form" method="post">
    {% csrf_token %}
    <h1 class="auth_h1">Do you really want to delete category "{{ category.name }}"?</h1>

    <input type="submit" class="auth_button" value="Yes">
</form>
    <a href="{% url 'admin:category_list' %}" class="auth_link">No</a>
</div>
{% endblock %}

adminapp/templates/adminapp/category_edit.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="container_auth container_admin_edit">
<form action="{% if request.resolver_match.url_name == 'category_edit' %}
{% url 'admin:category_edit' pk=category.pk %}{% else %}{% url 'admin:category_create' %}{% endif %}" class="auth_form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h1 class="auth_h1">Create/Edit category</h1>
    {% for field in form %}
    <div class="field_wrapper">
        {{ field.label_tag }}{{ field }}{{ field.errors }}
    </div>
    {% endfor %}
    <input type="submit" class="auth_button" value="Save">
</form>
    <a href="{% url 'admin:category_list' %}" class="auth_link">Back</a>
</div>
{% endblock %}

adminapp/templates/adminapp/category_list.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="container_auth container_admin_list">
    <div class="admin_object">
        <a href="{% url 'admin:category_create' %}" class="auth_link">+ Create a new category</a>
    </div>
    {% for category in categories %}
    <div class="admin_object">
        <h1 class="auth_h1">{{ category.name|title }}</h1>

        <a href="{% url 'admin:category_edit' pk=category.pk %}" class="auth_button">Edit</a>
        <a href="{% url 'admin:category_delete' pk=category.pk %}" class="auth_button">Delete</a>
    </div>
    {% endfor %}
</div>
{% endblock %}

adminapp/templates/adminapp/champion.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="container_auth">
    <img src="{{ object.image.url }}" alt="{{ object.name }}">
    <h1 class="auth_h1">{{ object.name }}</h1>
    <h1 class="auth_h1">{{ object.price_rp }} RP</h1>
    <h1 class="auth_h1">{{ object.price_be }} BE</h1>
    <h1 class="auth_h1">{{ object.role|title }}</h1>
    <a href="{% url 'admin:champion_list' %}" class="auth_link">Champions</a>
</div>
{% endblock %}

adminapp/templates/adminapp/champion_edit.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="container_auth container_admin_edit">
<form action="{% if request.resolver_match.url_name == 'champion_edit' %}
{% url 'admin:champion_edit' pk=object.pk %}{% else %}{% url 'admin:champion_create' %}{% endif %}" class="auth_form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h1 class="auth_h1">Create/Edit champion</h1>
    {% for field in form %}
    <div class="field_wrapper">
        {{ field.label_tag }}{{ field }}{{ field.errors }}
    </div>
    {% endfor %}
    <input type="submit" class="auth_button" value="Save">
</form>
    <a href="{% url 'admin:champion_list' %}" class="auth_link">Back</a>
</div>
{% endblock %}

adminapp/templates/adminapp/champion_list.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="container_auth container_admin_list">
    <div class="admin_object">
        <a href="{% url 'admin:champion_create' %}" class="auth_link">+ Create a new champion</a>
    </div>
    {% for champion in object_list %}
    <div class="admin_object">
        <a href="{% url 'admin:champion_detail' pk=champion.pk %}" class="auth_button"><h1 class="auth_h1">{{ champion.name|title }}</h1></a>

        <a href="{% url 'admin:champion_edit' pk=champion.pk %}" class="auth_button">Edit</a>
        <a href="{% url 'admin:champion_delete' pk=champion.pk %}" class="auth_button">Delete</a>
    </div>
    {% endfor %}
</div>
<div class="paginator_menu">
    {% if page_obj.has_previous %}
        <a href="{% url 'admin:champion_page' page_obj.previous_page_number %}">
            ↼&nbsp
        </a>
    {% else %}
        &nbsp&nbsp&nbsp
    {% endif %}
      <p>
          {% if page_obj %}
            {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}
          {% endif %}
      </p>
    {% if page_obj.has_next %}
        <a href="{% url 'admin:champion_page' page_obj.next_page_number %}">
            &nbsp⇁
        </a>
    {% else %}
        &nbsp&nbsp&nbsp
    {% endif %}

    </div>
{% endblock %}

adminapp/templates/adminapp/skin.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="container_auth">
    <img src="{{ object.image.url }}" alt="{{ object.name }}">
    <h1 class="auth_h1">{{ object.name }}</h1>
    <a href="{% url 'admin:champion_detail' pk=object.champion.pk %}" class="auth_button">
        <h1 class="auth_h1">{{ object.champion.name }}</h1>
    </a>
    <h1 class="auth_h1">{{ object.price_rp }} RP</h1>
    <h1 class="auth_h1">{{ object.division|title }}</h1>
    <a href="{% url 'admin:skin_list' %}" class="auth_link">Skins</a>
</div>
{% endblock %}

adminapp/templates/adminapp/skin_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="container_auth">
<form action="{% url 'admin:skin_delete' pk=object.pk %}" class="auth_form" method="post">
    {% csrf_token %}
    <h1 class="auth_h1">Do you really want to delete skin "{{ object.name }}"?</h1>

    <input type="submit" class="auth_button" value="Yes">
</form>
    <a href="{% url 'admin:skin_list' %}" class="auth_link">No</a>
</div>
{% endblock %}

adminapp/templates/adminapp/skin_edit.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="container_auth container_admin_edit">
<form action="{% if request.resolver_match.url_name == 'skin_edit' %}
{% url 'admin:skin_edit' pk=object.pk %}{% else %}{% url 'admin:skin_create' %}{% endif %}" class="auth_form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h1 class="auth_h1">Create/Edit skin</h1>
    {% for field in form %}
    <div class="field_wrapper">
        {{ field.label_tag }}{{ field }}{{ field.errors }}
    </div>
    {% endfor %}
    <input type="submit" class="auth_button" value="Save">
</form>
    <a href="{% url 'admin:skin_list' %}" class="auth_link">Back</a>
</div>
{% endblock %}

adminapp/templates/adminapp/skin_list.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="container_auth container_admin_list">
    <div class="admin_object">
        <a href="{% url 'admin:skin_create' %}" class="auth_link">+ Create a new skin</a>
    </div>
    {% for skin in object_list %}
    <div class="admin_object">
        <a href="{% url 'admin:skin_detail' pk=skin.pk %}" class="auth_button">
            <h1 class="auth_h1">{{ skin.name|title }}</h1>
        </a>

        <a href="{% url 'admin:skin_edit' pk=skin.pk %}" class="auth_button">Edit</a>
        <a href="{% url 'admin:skin_delete' pk=skin.pk %}" class="auth_button">Delete</a>
    </div>
    {% endfor %}
</div>
<div class="paginator_menu">
    {% if page_obj.has_previous %}
        <a href="{% url 'admin:skin_page' page_obj.previous_page_number %}">
            ↼&nbsp
        </a>
    {% else %}
        &nbsp&nbsp&nbsp
    {% endif %}
      <p>
          {% if page_obj %}
            {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}
          {% endif %}
      </p>
    {% if page_obj.has_next %}
        <a href="{% url 'admin:skin_page' page_obj.next_page_number %}">
             &nbsp⇁
        </a>
    {% else %}
        &nbsp&nbsp&nbsp
    {% endif %}

    </div>
{% endblock %}

adminapp/templates/adminapp/user.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="container_auth">
    <img src="{{ object.icon.url }}" alt="{{ object.name }}">
    <h1 class="auth_h1">{{ object.nickname }}</h1>
    <h1 class="auth_h1">{{ object.username }}</h1>
    <h1 class="auth_h1">{{ object.age }}</h1>
    <h1 class="auth_h1">{{ object.rp }} RP</h1>
    <h1 class="auth_h1">{{ object.blue_essence }} BE</h1>
    <h1 class="auth_h1">Active: {{ object.is_active }}</h1>
    <a href="{% url 'admin:user_list' %}" class="auth_link">Users</a>
</div>
{% endblock %}

adminapp/templates/adminapp/user_ban.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="container_auth">
<form action="{% url 'admin:user_delete' pk=user.pk %}" class="auth_form" method="post">
    {% csrf_token %}
    <h1 class="auth_h1">Do you really want to {% if not user.is_active %}un{% endif %}ban {{ user.nickname }}?</h1>

    <input type="submit" class="auth_button" value="Yes">
</form>
    <a href="{% url 'admin:user_list' %}" class="auth_link">No</a>
</div>
{% endblock %}

adminapp/templates/adminapp/user_edit.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="container_auth container_admin_edit">
<form action="{% if request.resolver_match.url_name == 'user_edit' %}
{% url 'admin:user_edit' pk=user.pk %}{% else %}{% url 'admin:user_create' %}{% endif %}" class="auth_form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h1 class="auth_h1">Create/Edit user</h1>
    {% for field in form %}
    <div class="field_wrapper">
        {{ field.label_tag }}{{ field }}{{ field.errors }}
    </div>
    {% endfor %}
    <input type="submit" class="auth_button" value="Save">
</form>
    <a href="{% url 'admin:user_list' %}" class="auth_link">Back</a>
</div>
{% endblock %}

adminapp/templates/adminapp/user_list.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="container_auth container_admin_list">
    <div class="admin_object">
        <a href="{% url 'admin:user_create' %}" class="auth_link">+ Create a new user</a>
    </div>
    {% for user in users %}
    <div {% if user.is_active %}class="admin_object"{% else %}class="admin_object not_active"{% endif %}>
        <a href="{% url 'admin:user_detail' pk=user.pk %}" class="auth_button">
            <h1 class="auth_h1">{{ user.nickname }}</h1>
        </a>

        <a href="{% url 'admin:user_edit' pk=user.pk %}" class="auth_button">Edit</a>
        <a href="{% url 'admin:user_delete' pk=user.pk %}" class="auth_button">{% if not user.is_active %}Unban
            {% else %}Ban{% endif %}</a>
    </div>
    {% endfor %}
</div>
<div class="paginator_menu">
    {% if page_obj.has_previous %}
        <a href="{% url 'admin:user_page' page_obj.previous_page_number %}">
            ↼&nbsp
        </a>
    {% else %}
        &nbsp&nbsp&nbsp
    {% endif %}
      <p>
          {% if page_obj %}
            {{ page_obj.number }}/{{ page_obj.paginator.num_pages }}
          {% endif %}
      </p>
    {% if page_obj.has_next %}
        <a href="{% url 'admin:user_page' page_obj.next_page_number %}">
            &nbsp⇁
        </a>
    {% else %}
        &nbsp&nbsp&nbsp
    {% endif %}

    </div>
{% endblock %}