lol/urls.py
from django.contrib import admin
from django.urls import path, re_path
from mainapp import views as mainapp
from authapp import views as authapp
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static


urlpatterns = [
    path('', authapp.index, name='index'),
    path('home/', mainapp.index, name="home"),
    path('collection/', include('collectapp.urls', namespace='collection')),
    path('loot/', include('lootapp.urls', namespace="loot")),
    path('store/', include('storeapp.urls', namespace="store")),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('social_django.urls', namespace='social')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('order/', include('orderapp.urls', namespace='order'))

    
    # path('control/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

orderapp/urls.py
from django.urls import path
import orderapp.views as orderapp

app_name = 'orderapp'

urlpatterns = [
    path('', orderapp.OrderListView.as_view(), name='list'),
    path('create/', orderapp.OrderCreateView.as_view(), name='create'),
    path('read/<int:pk>/', orderapp.OrderDetailView.as_view(), name='read'),
    path('update/<int:pk>/', orderapp.OrderUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', orderapp.OrderDeleteView.as_view(), name='delete'),
    path('proceed/<int:pk>/', orderapp.order_sending_to_payment, name='proceed'),
    path('payment/<int:pk>/', orderapp.order_payment, name='payment'),
    path('material/price/<int:pk>/', orderapp.get_material_price, name='get_material_price')
]

orderapp/models.py
from django.conf import settings
from django.db import models
from lootapp.models import Material
from django.dispatch import receiver
from django.db.models.signals import post_save, pre_delete, pre_save
from django.db.models import Q


class Order(models.Model):

    STATUS_FORMING = 'FM'
    STATUS_SEND_TO_PAYMENT = 'STP'
    STATUS_PAID = 'PD'
    STATUS_DONE = 'DN'
    STATUS_CANCELED = 'CN'

    STATUSES = ((STATUS_FORMING, "Forming"),
                (STATUS_SEND_TO_PAYMENT, "Waiting for payment"),
                (STATUS_PAID, "Paid"),
                (STATUS_DONE, "Done"),
                (STATUS_CANCELED, "Canceled"))

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    status = models.CharField(choices=STATUSES, default=STATUS_FORMING, max_length=3)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)

    def get_summary(self):
        _items = self.orderitems.select_related()
        return {
            'total_cost': sum(list(map(lambda x: x.cost, _items))),
            'total_quantity': sum(list(map(lambda x: x.quantity, _items)))
        }

    @property
    def total_cost(self):
        _items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.cost, _items)))

    @property
    def total_quantity(self):
        _items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, _items)))

    def delete(self):
        for item in self.orderitems.select_related():
            item.delete()
        self.is_active = False
        self.status = self.STATUS_CANCELED
        self.save()


class OrderItem(models.Model):

    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='orderitems')
    material = models.ForeignKey(Material, on_delete=models.CASCADE, verbose_name='Material',
                                 limit_choices_to=Q(is_purchasable=True))
    quantity = models.PositiveIntegerField(default=0, verbose_name='Quantity', )

    @property
    def cost(self):
        return self.material.price_rp * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.get(pk=pk)


@receiver(post_save, sender=OrderItem)
def item_post_save_adjustments(sender, update_fields, instance, **kwargs):
    if instance.quantity == 0:
        instance.delete()
    try:
        item = OrderItem.objects.get(Q(order=instance.order, material=instance.material), ~Q(pk=instance.pk))
        item.quantity += instance.quantity
        instance.delete()
        item.save()
    except (OrderItem.DoesNotExist, AssertionError):
        pass


@receiver(pre_save, sender=OrderItem)
def material_quantity_update_save(sender, update_fields, instance, **kwargs):
    if instance.pk:
        instance.material.quantity -= instance.quantity - instance.get_item(instance.pk).quantity
    else:
        instance.material.quantity -= instance.quantity
    instance.material.save()


@receiver(pre_delete, sender=OrderItem)
def material_quantity_update_delete(sender, instance, **kwargs):
    instance.material.quantity += instance.quantity
    instance.material.save()

orderapp/forms.py
from django import forms

from orderapp.models import Order, OrderItem


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        exclude = ('user', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class OrderItemForm(forms.ModelForm):

    price = forms.CharField(label='price', required=False)

    class Meta:
        model = Order
        exclude = ()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

orderapp/views.py
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from orderapp.models import Order, OrderItem

from orderapp.forms import OrderItemForm, OrderForm

from lootapp.models import PurchasedMaterial

from lootapp.models import Material


class OrderListView(ListView):
    model = Order

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(ListView, self).dispatch(*args, **kwargs)


class OrderCreateView(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('order:list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST)
        else:
            formset = OrderFormSet()
        context_data['orderitems'] = formset
        return context_data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.total_cost == 0:
            self.object.delete()

        return super().form_valid(form)

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(CreateView, self).dispatch(*args, **kwargs)


class OrderUpdateView(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('order:list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        OrderFormSet = inlineformset_factory(Order, OrderItem, OrderItemForm, extra=1)

        if self.request.POST:
            formset = OrderFormSet(self.request.POST, instance=self.object)
        else:
            formset = OrderFormSet(instance=self.object)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.material.price_rp

        context_data['orderitems'] = formset
        return context_data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        if self.object.total_cost == 0:
            self.object.delete()

        return super().form_valid(form)

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(UpdateView, self).dispatch(*args, **kwargs)


class OrderDetailView(DetailView):
    model = Order

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(DetailView, self).dispatch(*args, **kwargs)


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy('order:list')

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(DeleteView, self).dispatch(*args, **kwargs)


def order_sending_to_payment(request, pk):
    order = Order.objects.get(pk=pk)
    order.status = Order.STATUS_SEND_TO_PAYMENT
    order.save()
    return HttpResponseRedirect(reverse('order:payment', kwargs={'pk': pk}))


def order_payment(request, pk):
    order = Order.objects.get(pk=pk)
    if order.user.rp >= order.total_cost:
        order.user.subtract_rp(order.total_cost)
        order.status = Order.STATUS_PAID
        order.save()
        for item in OrderItem.objects.filter(order=order):
            purchased = PurchasedMaterial(material=item.material, user=order.user, quantity=item.quantity)
            purchased.save()
        order.status = Order.STATUS_DONE
        order.save()
    return HttpResponseRedirect(reverse('order:list'))


def get_material_price(request, pk):
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        material_item = Material.objects.filter(pk=pk).first()
        if material_item:
            return JsonResponse({'price': material_item.price_rp})
        else:
            return JsonResponse({'price': 0})

orderapp/templates/orderapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{{ title|title }}{% endblock %}</title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <link rel="stylesheet" href="{% static 'css/fonts.css'%}">
    {% endblock %}
    {% block js %}
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.formset.js' %}"></script>
       <script src="{% static 'js/orders.js' %}"></script>
    {% endblock %}
</head>

<body>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
</body>

</html>

orderapp/templates/orderapp/order_confirm_delete.html
{% extends 'orderapp/base.html' %}
{% load static %}
{% block content %}
<div class="order_block">
       <div class="order_text">Are you sure?</div>
       <form action="{% url 'order:delete' object.pk %}" method="post">
           {% csrf_token %}
           <input class="order_button" type="submit" value="Delete">
       </form>
           <a href="{% url 'order:list' %}" class="order_button">Cancel</a>
   </div>

{% endblock %}

orderapp/templates/orderapp/order_detail.html
{% extends 'orderapp/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
{% include 'orderapp/includes/inc_summary.html' %}
<div class="order_block">
       {% for item in object.orderitems.select_related %}
           <div class="order_item">
               <img src="{{ item.material.image|loot }}"
                    alt="{{ item.material.name }}">
               <div> {{ item.material.name }} </div>
               <div> {{ item.material.price_rp }} RP
                   x {{ item.quantity }}
                   = {{ item.cost }} RP </div>
           </div>
       {% endfor %}
    <div class="order_button_block">
       {% if object.status == "FM" or object.status == "STP" %}
           <a href="{% url 'order:delete' object.pk %}" class="order_button">Delete</a>
       {% endif %}
       {% if object.status == 'FM' %}
        <a href="{% url 'order:update' object.pk %}" class="order_button">Update</a>
           <a href="{% url 'order:proceed' object.pk %}" class="order_button">Buy</a>
       {% elif object.status == 'STP' %}
           <a href="{% url 'order:payment' object.pk %}" class="order_button">Pay</a>
       {% endif %}
           <a href="{% url 'order:list' %}" class="order_button">Go back</a>
           <a href="{% url 'home' %}" class="order_button">Home</a>
        </div>
   </div>

{% endblock %}

orderapp/templates/orderapp/order_form.html
{% extends 'orderapp/base.html' %}
{% load static %}
{% load cache %}
{% block content %}
{% include 'orderapp/includes/inc_summary.html' %}
<div class="order_block order_form">
       <form action="" method="post">
           {% csrf_token %}
           {{ form.as_p }}
           <table class="order_table">
               {{ orderitems.management_form }}
               {% for form in orderitems.forms %}
                   {% if forloop.first %}
                       <thead>
                       <tr class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                           {% for field in form.visible_fields %}
                               <th class="order_table_titles">
                                   {{ field.label|capfirst }}
                               </th>
                           {% endfor %}
                       </tr>
                       </thead>
                   {% endif %}
                   <tr class="order_table_line">
                       {% for field in form.visible_fields %}
                           <td  class="{% cycle 'td1' 'td2' 'td3' %} order formset_td">
                               {% if forloop.first %}
                                   {% for hidden in form.hidden_fields %}
                                       {{ hidden }}
                                   {% endfor %}
                               {% endif %}
                               {{ field.errors.as_ul }}
                               {% if field.name != 'price' %}
                                    {% if field.name == 'product' %}
                                        {% cache 3600 orderitemform_product field.value %}
                                            {{ field }}
                                        {% endcache %}
                                    {% else %}
                                        {{ field }}
                                    {% endif %}
                               {% else %}
                                    {% if field.value %}
                                        <span class="orderitems-{{forloop.parentloop.counter0}}-price">
                                            {{ field.value }}</span> RP
                                    {% endif %}
                               {% endif %}
                           </td>
                       {% endfor %}
                   </tr>
               {% endfor %}
           </table>
           <div class="order_button_block">
           <button type="submit" value="submit" class="order_button">Save</button>
           {% if object and object.status == 'FM' %}
           <a href="{% url 'order:delete' object.pk %}" class="order_button">Delete</a>
               {% elif object and object.status == 'STP' %}
           <a href="{% url 'order:proceed' object.pk %}" class="order_button">Buy</a>
           {% endif %}
           <a href="{% url 'order:list' %}" class="order_button">Go back</a>
           <a href="{% url 'home' %}" class="order_button">Home</a>
           </div>
       </form>
   </div>

{% endblock %}

orderapp/templates/orderapp/order_list.html
{% extends 'orderapp/base.html' %}
{% load static %}
{% block content %}
<div class="order_block">
<div class="order_text">
    Your purchases, {{ user.nickname|title}}
</div>
<table class="order_table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Created</th>
        <th>Last update</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
        {% for item in object_list %}
            {% if item.is_active %}
            <tr>
                <td>{{ item.pk }}</td>
                <td>{{ item.created_at|date:"Y-m-d H:i:s" }}</td>
                <td>{{ item.updated_at|date:"Y-m-d H:i:s" }}</td>
                <td>{{ item.get_status_display }}</td>
                <td>
                    <a href="{% url 'order:read' item.pk %}">
                        Details
                    </a>
                </td>
                <td>
                    {% if item.status == 'FM' %}
                      <a href="{% url 'order:update' item.pk %}">
                        Update
                      </a>
                    {% endif %}
                </td>
                <td>
                    {% if item.status == 'FM' %}
                      <a href="{% url 'order:delete' item.pk %}">
                          Delete
                      </a>
                    {% endif %}
                </td>
                <td>
                    {% if item.status == 'STP' %}
                      <a href="{% url 'order:payment' item.pk %}">
                          Pay
                      </a>
                    {% endif %}
                </td>
            </tr>
            {% endif %}
        {% endfor %}
    </tbody>
</table>
<div class="order_button_block">
    <a href="{% url 'home' %}" class="order_button">
        Home
    </a>
    <a href="{% url 'order:create' %}" class="order_button">
        New order
    </a>
</div>
</div>
{% endblock %}