adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', adminapp.user_list, name='user_list'),
    path('users/read/<int:page>/', adminapp.user_list, name='user_page'),
    path('users/update/<int:pk>/', adminapp.user_edit, name='user_edit'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),
    path('users/detail/<int:pk>/', adminapp.UserDetailView.as_view(), name='user_detail'),

    path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.category_list, name='category_list'),
    path('categories/update/<int:pk>/', adminapp.category_edit, name='category_edit'),
    path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),

    path('champions/create/', adminapp.ChampionCreateView.as_view(), name='champion_create'),
    path('champions/read/', adminapp.ChampionListView.as_view(), name='champion_list'),
    path('champions/read/<int:page>/', adminapp.ChampionListView.as_view(), name='champion_page'),
    path('champions/update/<int:pk>/', adminapp.ChampionUpdateView.as_view(), name='champion_edit'),
    path('champions/delete/<int:pk>/', adminapp.ChampionDeleteView.as_view(), name='champion_delete'),
    path('champions/detail/<int:pk>/', adminapp.ChampionDetailView.as_view(), name='champion_detail'),

    path('skins/create/', adminapp.SkinCreateView.as_view(), name='skin_create'),
    path('skins/read/', adminapp.SkinListView.as_view(), name='skin_list'),
    path('skins/read/<int:page>/', adminapp.SkinListView.as_view(), name='skin_page'),
    path('skins/update/<int:pk>/', adminapp.SkinUpdateView.as_view(), name='skin_edit'),
    path('skins/delete/<int:pk>/', adminapp.SkinDeleteView.as_view(), name='skin_delete'),
    path('skins/detail/<int:pk>/', adminapp.SkinDetailView.as_view(), name='skin_detail')
]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<email>/<key>/', authapp.verify, name='verify')
]

lol/urls.py
from django.contrib import admin
from django.urls import path, re_path
from mainapp import views as mainapp
from authapp import views as authapp
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static


urlpatterns = [
    path('', authapp.index, name='index'),
    path('home/', mainapp.index, name="home"),
    path('collection/', include('collectapp.urls', namespace='collection')),
    path('loot/', include('lootapp.urls', namespace="loot")),
    path('store/', include('storeapp.urls', namespace="store")),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('social_django.urls', namespace='social')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('order/', include('orderapp.urls', namespace='order'))

    
    # path('control/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mainapp/models.py
from django.db import models


class CollectionCategory(models.Model):
    name = models.CharField(verbose_name='name', max_length=32, unique=True)
    image = models.ImageField(verbose_name='loot image', blank=True)

    def __str__(self):
        return self.name


class Champion(models.Model):
    category = models.ForeignKey(CollectionCategory, on_delete=models.CASCADE, verbose_name='category')
    name = models.CharField(verbose_name='name', max_length=32, unique=True)
    image = models.ImageField(upload_to='champions', blank=True)
    price_rp = models.PositiveBigIntegerField(verbose_name='price rp')
    price_be = models.PositiveBigIntegerField(verbose_name='price blue essence')
    role = models.CharField(verbose_name='role', max_length=16)
    role_b = models.CharField(verbose_name='second role', max_length=16, blank=True)

    def __str__(self):
        return self.name


class Icon(models.Model):
    name = models.CharField(verbose_name='name', unique=True, max_length=32)
    image = models.ImageField(verbose_name='image')

    def __str__(self):
        return self.name


class Skin(models.Model):
    category = models.ForeignKey(CollectionCategory, on_delete=models.CASCADE, verbose_name='category')
    champion = models.ForeignKey(Champion, on_delete=models.CASCADE, verbose_name='champion')
    name = models.CharField(verbose_name='name', max_length=32, unique=True)
    image = models.ImageField(upload_to='skins', blank=True)
    price_rp = models.PositiveBigIntegerField(verbose_name='price_rp')
    division = models.CharField(verbose_name='division', max_length=16, blank=True)

    def __str__(self):
        return self.name

mainapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


@login_required
def index(request):
    context = {
        'title': 'Home',
        'player': request.user
    }
    return render(request, 'mainapp/index.html', context=context)

mainapp/templates/mainapp/base.html
{% load static %}
{% load my_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{{ title|title }}{% endblock %}</title>
    {% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <link rel="stylesheet" href="{% static 'css/fonts.css'%}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>

<body>
    <div class="container">
        {% block header %}
        <hr class="top_line">
        <div class="header">
            <div class="header_left">
                <img src="{% static 'img/LOL_icon.svg' %}" alt="logo" class="header_logo">
                <hr class="header_line">
                <a href="{% url 'home' %}" class="header_home">Home</a>
                {% if request.user.is_superuser %}
                <a href="{% url 'admin:user_list' %}" class="header_home">Admin</a>
                {% endif %}
            </div>
            <div class="header_right">
                {% include 'mainapp/includes/inc_main_menu.html' %}
                <hr class="header_line">
                <div class="header_currency">
                    <div class="header_currency_subblock">
                        <img src="{% static 'img/RP.svg' %}" alt="rp" class="currency_img">
                        <h4 class="rp_count">{{ player.rp }}</h1>
                    </div>
                    <div class="header_currency_subblock">
                        <img src="{% static 'img/Blue_Essence.svg' %}" alt="blue essence" class="currency_img">
                        <h4 class="blue_count">{{ player.blue_essence }}</h1>
                    </div>
                </div>
                <div class="header_user">
                    <div class="user_icon_block">
                        <img src="{{ user.icon.url|icon_default }}" alt="icon" class="user_icon">
                    </div>
                    <div class="user_right">
                        <h4 class="user_name">{{ user.nickname|default:'Player' }}</h4>
                        <div class="user_menu">
                            <a href="{% url 'auth:edit' %}" class="user_menu_link">Edit</a>
                            <a href="{% url 'auth:logout' %}" class="user_menu_link">Logout</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <hr class="mid_line">
        {% endblock %}
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

mainapp/templates/mainapp/loot.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="loot_content">
    <div class="loot_menu">

        {% include 'mainapp/includes/inc_loot_menu.html' %}
    </div>
    <div class="loot_left">

    </div>
    <div class="loot_right">

    </div>
</div>
{% endblock %}